# actable的配置信息
actable:
  table:
    auto: update
  model:
    pack: com.hadymic.sqlgenerator.splash.model
  database:
    type: mysql
# mybatis的配置信息，key也可能是：mybatis.mapper-locations
mybatis:
  mapperLocations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#log
logging:
  file:
    path: D:\\IdeaProjects\\Sqlgenerator\\log
#    name: sqlgenerator.log
  level:
    root: INFO

ad:
  file:
    filePath: D:/file